name: 'RocketChat Node Notifier'
description: 'Отправка уведомлений в RocketChat'
inputs:
  url:
    required: true
  template:
    required: false
    default: 'custom'
    description: 'deploy_success, audit_error, custom'
  text:
    required: false
  params:
    required: false
    description: 'Параметры в формате КЛЮЧ|ЗНАЧЕНИЕ'
  alias:
    default: 'Gitea Bot'
    required: false
  avatar:
    default: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/gitea.svg'
    required: false
  color:
    default: '#00ff00'
    required: false
  links:
    required: false

runs:
  using: 'node20'
  main: 'index.js'